trigger:
- master

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: 'shasbDockerHub'
  imageRepository: 'shashankbarsin/builddemo'
  dockerfilePath: '**/app/Dockerfile'
  tag: '$(Build.BuildId)'
  
  # Kubernetes Namespace
  aksk8sNamespace: 'aksnamespace'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build job
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          
    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: 'manifests'
        targetPath: 'manifests'

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Deploy job 1
    pool:
      vmImage: $(vmImageName)
    environment: 'shasb.aksnamespace'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@1
            inputs:
              artifactName: 'manifests'
              downloadPath: '$(System.ArtifactsDirectory)/manifests'
              
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              namespace: $(aksk8sNamespace)
              manifests: |
                $(System.ArtifactsDirectory)/manifests/*
              containers: |
                $(imageRepository):$(tag)
